// Conversations and messages API. AI responses are generated by the backend;
// the client never calls Vertex AI directly.
import { get, post, patch, del } from './api';

const BASE = '/api/conversations';
const conv = (id) => `${BASE}/${encodeURIComponent(id)}`;

export const getConversations = () => get(BASE);
export const getConversation = (id) => get(conv(id));
export const createConversation = (data = {}) => post(BASE, data);
export const updateConversation = (id, data) => patch(conv(id), data);
export const renameConversation = (id, title) => updateConversation(id, { title });
export const archiveConversation = (id) => updateConversation(id, { archived: true });
export const deleteConversation = (id) => del(conv(id));

export const getMessages = (id) => get(`${conv(id)}/messages`);

// flags: { isSearch, isDeepResearch, isCriticalAnalysis }
// Returns { userMessage, assistantMessage }.
export const sendMessage = (id, content, flags = {}) => post(`${conv(id)}/messages`, { content, ...flags });

export const editMessage = (id, messageId, content) =>
  patch(`${conv(id)}/messages/${encodeURIComponent(messageId)}`, { content });

// Replaces an assistant message (and anything after it) with a new response.
export const regenerateMessage = (id, messageId) =>
  post(`${conv(id)}/messages/${encodeURIComponent(messageId)}/regenerate`);
