// Conversations and messages API. AI responses are generated by the backend;
// the client never calls Vertex AI directly.
import { get, post, put, patch, del } from './api';

const BASE = '/api/conversations';
const conv = (id) => `${BASE}/${encodeURIComponent(id)}`;

export const getConversations = () => get(BASE);
export const getConversation = (id) => get(conv(id));
export const createConversation = (data = {}) => post(BASE, data);
export const updateConversation = (id, data) => patch(conv(id), data);
export const renameConversation = (id, title) => updateConversation(id, { title });
export const archiveConversation = (id) => updateConversation(id, { archived: true });
export const deleteConversation = (id) => del(conv(id));

export const getMessages = (id) => get(`${conv(id)}/messages`);

// options.search: answer using Google Search (the reply carries metadata.sources).
// options.attachments: [{ name, mimeType, data (base64) }] read by the AI with this message.
// Returns { userMessage, assistantMessage }.
// The browser's time zone is sent so Athena understands "tomorrow at 6pm".
// The reply's metadata.actions lists anything Athena changed (tasks, journal, calendar…).
export const sendMessage = (id, content, { search = false, attachments = [] } = {}) =>
  post(`${conv(id)}/messages`, {
    content,
    timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    ...(search ? { search } : {}),
    ...(attachments.length ? { attachments } : {}),
  });

// rating: 'up' | 'down' | null (clears).
export const rateMessage = (id, messageId, rating) =>
  put(`${conv(id)}/messages/${encodeURIComponent(messageId)}/rating`, { rating });

export const editMessage = (id, messageId, content) =>
  patch(`${conv(id)}/messages/${encodeURIComponent(messageId)}`, { content });

// Replaces an assistant message (and anything after it) with a new response.
export const regenerateMessage = (id, messageId) =>
  post(`${conv(id)}/messages/${encodeURIComponent(messageId)}/regenerate`);
